services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - ./migrations/init:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
  
volumes:
  postgres_data: